JPA
Dimitriy1/Lab9 pull request #1
Opened 2019-01-18 13:42 UTC by Dimitriy1

2019-01-18 15:11 UTC, BondarenkoJek requested changes

2019-01-18 15:11 UTC, BondarenkoJek commented on src/main/java/mate/academy/jpademo/Main.java
> +
line not need

2019-01-18 15:11 UTC, BondarenkoJek commented on src/main/java/mate/academy/jpademo/Main.java
> +
line not need

2019-01-18 15:11 UTC, BondarenkoJek commented on src/main/java/mate/academy/jpademo/model/Patient.java
> +import java.util.List;
You don't use List

2019-01-18 15:11 UTC, BondarenkoJek commented on src/main/java/mate/academy/jpademo/model/accessory/UltrasonicAccessory.java
> +import javax.persistence.Table;
You don't use annotation "Table"

2019-01-18 15:11 UTC, BondarenkoJek commented on src/main/java/mate/academy/jpademo/service/PatientService.java
> +import java.util.List;
You don't use List

2019-01-18 15:11 UTC, BondarenkoJek commented on src/main/java/mate/academy/jpademo/service/TestService.java
> +import java.util.List;
You don't use List

2019-01-18 15:11 UTC, BondarenkoJek commented on src/main/java/mate/academy/jpademo/service/impl/PatientServiceImpl.java
> +    PatientDao patienceDao;
private

2019-01-18 15:11 UTC, BondarenkoJek commented on src/main/java/mate/academy/jpademo/dao/impl/PatientDaoImpl.java
> +
line not need

2019-01-18 15:11 UTC, BondarenkoJek commented on src/main/java/mate/academy/jpademo/model/test/SkinTest.java
> +    Double dryness;
private

2019-01-19 03:42 UTC, BondarenkoJek approved these changes
LGTM

2019-01-19 15:05 UTC, boroda4436 approved these changes
LGTM

2019-01-20 16:49 UTC, merged